
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: sgt_order_filter_JPM
      description: "Estado de Ordenes"
      columns:
          - name: status
            description: "Estado de ordenes"
            tests:
                - not_null
                - accepted_values:
                    values: ['placed','shipped']